Arun9739/Paryatana

contact.html

- Issue No. #17
- Links are attached to the icons present in the contacts.
The links are added so that the icons becomes responsive and functional.

links added to the contacts icon

---

tours.html

- #7
- updated dates to be unique
- replaced lorem ipsum text with a brief description of the respective place.
Added CSS icons to make it look more attractive. ( calendar and quote)
Dates are according to the best time to visit the respective places
This change is required to maintain the look and feel of the website as well as provide users with more information regarding travelling.
**BEFORE**:
**AFTER**:

Added proper content with unique dates in tour

---

css/templatemo-style.css

- Issue No. #18
- I made the position of the navbar header fixed at the top and also added an additional margin on the " tm-header" class to replace the space earlier covered by the header.
I also made the header fit the whole screen for all screens
Earlier the navbar used to scroll up along with the content of the website hence making it very much hard for the user to instantly change the page.

Made Navbar fixed at the top on scroll

---

about.html
contact.html
css/scrollToTop.css
index.html
js/scrollToTop.js
tours.html

- Issue No. #13 
- Added a scroll to top button
It solves the issue of scrolling through the entire page again to reach the top of the page.

Added Scroll to Top Button

---

contact.html
js/email.js

- Issue No. #23 
- I added a js/email.js file to handle email and its content
- Added onclick eventHandler to the contact form to call `sendEmail(`) function
1. email.js expose a sendEmail function
2. email.js script was included in contact.html
3. sendEmail function collects all the data from the form field by DOM manipulation
4. And finally open an Email client on the local machine, where all the fields e,g- Subject, To, Body were already available
` window.open('mailto:your@email.address?subject='+subject+'&body='+body);`
- With this feature, that user who wants to contact can send their message to the concerned authority

Send email by clicking SUBMIT button

---

contact.html

- Issue No. #51 
- Corrected the spelling of "Paryatana" in the navbar of contacts page
As it is the website name, it must be correct everywhere otherwise it could create a false impression on the visitors.

Corrected spelling of the website name in the contact page

---

about.html
index.html
tours.html

- Issue No. #4 
- Added functionality to the Learn More button to help users reach the various tours and packages by clicking the learn more button.
It helps users reach the various available tours and packages with the ease of a click.

Added functionality to the Learn More button

---

css/templatemo-style.css
tours.html

- Issue No. #63
- Aligned the boxes in Our  Tour section in our tour page
Before: 
After:

Aligned Boxes under our Tour section in Our Tour page

---

about.html
css/templatemo-style.css

- Issue No. #66
added shadow effect to the founders card and added hover effect to social icons added a line separator in testimonial section 
- 
shadow effect to the founders card and added hover effect to social icons added a line separator in testimonial section 
All these changes comes in UI enhancement this helps to improve the user interaction with page  
- [ x] I have followed code style of this project.
- [x ] The website is properly working after my changes.
- [ x] New feature (non-breaking change which adds functionality)

Added styling to about us page cards and icons

---

css/templatemo-style.css

- Issue No. #96 
- Removed sizes coded in px and replaced them with flexbox logic
This will help make the page more responsive, and look better on smaller screens

fixed use of hardcoded values for links on the homepage

---

about.html
css/templatemo-style.css

- Issue No. #88
- About html
-CSS
Sir I have made a comment box using HTML and CSS only as when doing with php..I need to change the filename which I think would not be appropriate (from .html to .php) as .htaccess is not working on my local machine..
In my previous PR, I had a branch conflict so I made this by updating all and resolving it
It makes people who have went along with your services to interact with each other or raise a question regarding services.
- [ x] 🌟 ed the repo
- [ x] Bug fix (non-breaking …

Added Commen Section for Interactivity

---

index.html

I've added trendy card design with cool hover effect.
- Issue No. #104 
- Added Trendy Card Design
- Modified Basic Cards Design To Trendy Cards Design (Glassmorphisim CSS)
This card design will look more catchy and trendy than the previous one.
This change is required to give the website modern look.

Added Trendy Card Design

---

about.html

- Issue No. #97 
- I have made the hover effect more smooth by adding transition to it in About page on WHO WE ARE SECTION .
- Also added space and margins between two cards in Mobile View which make the animation more perfect and smooth. 
-I have added more gaps between the two cards in Mobile View so that the animation looks more perfect 
https://user-images.githubusercontent.com/106610708/194381597-c7ca17d8-fff9-4f90-b787-b22dbdd00216.mp4
###After
https://user-images.githubusercontent.com/106610708/194382114-e4fd34bf-24b4-4532-9bdf-c951ebf0f39f.mp4

added smooth animation and responsiveness

---

about.html
contact.html
css/templatemo-style.css
favourites.html
index.html
tours.html

- Issue No. #102 
- Attached developer profile link with the developer name in copyright section.
https://user-images.githubusercontent.com/75976169/194460846-c5bfac87-4df7-4c54-ae16-2d9a3d9b4d45.mp4

Added developer profile link in copyright section

---

index.html

- Issue No. #9 
- changed the lorem ipsum text to proper text respective to place visiting
- its a visual aspect change and helps in understanding the 'Popular Package'

updated catchphrases for popular packages

---

about.html
contact.html
favourites.html
tours.html

- Issue No. #128 
I have now made the favicon visible on all the pages.

Fix favicon

---

css/templatemo-style.css
index.html

Reverts Arun9739/Paryatana#132

Revert "fixed the card responsiveness for tablet view in home page"

---

about.html
contact.html
css/templatemo-style.css
index.html
tours.html

Reverts Arun9739/Paryatana#160

Revert "Master"

---

css/templatemo-style.css

- Issue No. #154
- Added box shadow and on hover box shadows to places cards on home and tours pages
Home page:
On hover:

Added box shadow to places cards

---

contact.html

I have removed extra social links which is not usefull as footer section already contained it
- Issue No. #157 
- I have removed unnecessary extra social links which didn't even had any images on it.
I have removed unnecessary extra social links which didn't even had any images on it mainly as it was already updated in footer section and thus was looking unattractive with it.
I think removal of those social links should be appropriate solution as the footer section already address that problem.
This removes the broken social icons as well as eliminates duplicate social buttons within a small UI area
- [ z ] I have followed code style of this project.
- [ x ] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [ x ] All the …

Removed un-necessay extra social links

---

css/bootstrap.min.css
css/font-awesome.min.css
css/templatemo-style.css
index.html

- Issue No. #165
- Improved the input field UI
- added active hover effects to the input field to make it more user friendly
- aligned the card vertically with the other cards.
- UI of the application is a major part and it is always a good practice to maintain all the elements in the web page aligned with each other.
-  Also hover and active effects make the user interaction fine tuned.
- [] Bug fix (non-breaking change which fixes an issue)
@Arun9739 please merge my PR

Added hover and active effects to input fields and Fixed card alignment issue

---

about.html
contact.html
css/templatemo-style.css
index.html
tours.html

The Links and the buttons of the websites are improved and different hovering affects are applied on it.
- Issue No. #170 
1. Buttons of the navigation bar is improved, border shadow effect on hovering is applied.
2. Border shadow on hovering is applied on the "Check Now" button in Home section.
3. Enlarge and background color change on hovering applied on the social media icons in the footer section.
4. Color change on hovering applied on the "Home","About","Our Tour" and "Contact" buttons in footer section.

Buttons and links styling improved

---

tours.html

- Issue No. #187 
- Corrected the shadow effect that wasn't working previously

Shadow effect of Our Tours corrected

---

index.html

Added more option for hotel and car
- Issue No. #218
- Added More selection option for hotels and car model 
- [ x] I have followed code style of this project.
- [x ] The website is properly working after my changes.
- [ x] 🌟 ed the repo
- [ x] New feature (non-breaking change which adds functionality)

Added More Option

---

css/bootstrap.min.css
favourites.html
index.html
tours.html

- Issue No. #209 
- Made changes to "form-group" class css and fixed the margin.
- Fixed the background issue in the hotel/car rental card
- Made the content center-aligned and removed the uneven margin/spacing in the card.
- It fixes the issue of unevenness, which made the card and thus the landing page UI not so great.
Before:
After:

fixed the margin issue and background coloring

---

css/footer.css
css/logo.css

- Issue No. #215 
- Added Responsiveness to Logo at 991px in Navbar and at 630px in Footer.
- Initially the Navbar and Footer Logo was not Responsive for Screen sizes 991px and 630px, I made it to fit inside at these screen sizes and added responsiveness.
- This change makes the website look more professional and asthetic.
https://user-images.githubusercontent.com/113718835/195426951-76116128-32b7-4ca0-80ca-aac813ada144.mp4

Responsive Logo in Navbar and Footer.

---

index.html

- Issue No. #193 .
- Added Transition Effects in Card.
Added Hover Effect which displays description about that destination providing a more user friendly experience.

New Commit on effect

---

index.html

Reverts Arun9739/Paryatana#250

Revert "New Commit on effect"

---

about.html
contact.html
index.html
tours.html

- Issue No. #235 
- Fixed the fav icon bug of the title bar

Fixed fav icon error in title bar

---

favourites.html

- Issue No. #237 
- I've added the Footer in favourite.html page
To make the website more attractive.

I've fixed the footer in favourite.html

---

index.html
js/date-check.js

BUG:
It is processing the request even if the dates are in following format
check-in date > check-out date
check-in date < current date
check-out date < current date
same pattern for car rental
FIX:
Solution is to check the date to follow these condition then only process
check-in date <= check-out date
check-in date >= current date
check-out date >= current date
otherwise show alert box
- Issue No. #201
- Added date-check.js
- form date get validation from functions in date-check.js
- on true it will get submit, otherwise show alert without submitting

Bug Fix: Validation for invalid dates

---

about.html

- Issue No. #258
- Make cards float on hover
- Change box-shadow
- Change the transformation on hover

Fix issue #258

---

css/footer.css

- Issue No. #242 
- Added Border Bottom to Footer Follow Us Text
-The Follow Us text was looking little weird with underline text style so I decided to give border and padding giving will be the good option for that 
- It make the follow us text in footer looks little good

Updated Footer Followup Design

---

about.html

- Issue No. #244 
- Added the text for the website thus enhancing the user experience.

Added text instead of lorem ipsum

---

contact.html

**The CONTACT Page form is working now and the email is sent using Formspree**
- Issue No.  #223 
- I made the CONTACT us form woking i.e. whenever the user submit details the response will get recorded and sent via mail
**Currently all the form responses is directed to my mail id. @Arun9739 if you want I can direct them to your mail id you just need to verify it on formspree.**

Contact form is now working

---

about.html

- Issue No. #246 
- Provided the social media links as you wanted
Links to the social media platforms
For Twitter

Added links for all social media 

---

about.html
css/templatemo-style.css

- Issue No. #277
- Fix the content adjustment issue in the testimonial card in the "about us" section.
Changed the padding of the class "tm-testimonials-content in the CSS of the about us page

fixed the testimonial card issue

---

css/footer.css

- Issue No. #271 
- Added media queries for mobile veiw
It fixes the misalignment of footer in mobile veiw

footer responsiveness fixed

---

css/templatemo-style.css

- Issue No. #287 
- 
HOVER EFFECT CHANGED
- [x ] I have followed the code style of this project.
- [x ] All the aspects mentioned in the issue are covered.
- [x ] The website is properly working after my changes.
- [x ] 🌟 ed the repo
- [ x] New feature (non-breaking change which adds functionality)

UI Enhancement

---

about.html
contact.html
css/footer.css
favourites.html
index.html
tours.html

issue no #289

---

about.html
favourites.html
tours.html

- Issue No. #307 
- Wrote code to open the links in a new tab
- corrected links and the respective names given on pages
- created input field for mail to sign-in for newsletter
- created a proper feedback to be given to user once their mail-id is submitted for newsletter

Link functionalities

---

css/parallax-only.css
index.html

- Issue No. #311
- Background is changed to linear-gradient
- And font color is more consistent with the webpage
background: linear-gradient(180deg, rgba(252,221,68,1) 70%, rgba(255,255,255,1) 100%);
color: #400361;

Fix: Bgrd & color of "YOUR GO TO TRAVEL PARTNER"

---

contact.html
css/footer.css
css/templatemo-style.css

- Issue No. [#323](https://github.com/Arun9739/Paryatana/issues/323)
Enhance contact page
- 
- [ yes] I have followed code style of this project.
- [ yes] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [ yes] All the aspects mentioned in the issue are covered.
- [ yes] The website is properly working after my changes.
- [ yes] 🌟 ed the repo
- [ no] Bug fix (non-breaking change which fixes an issue)
- [yes ] New feature (non-breaking change which adds functionality)

Enhance contact page

---

about.html
css/scrollToTop.css

- Issue No. # 327
- resolved overflow issue
- Before
- After

issue resolved

---

css/hero.css
index.html

- Issue No. #317 
- Changed the Hero section  of the website
Added background images and cards with a discover button which links to the visit card section.
- [x ] 🌟 ed the repo
- [x ] Bug fix (non-breaking change which fixes an issue)

Updated the "your go to travel partner" section

---

tours.html

- Issue No. #324 
- I have added random dates, special packages will now show dates of the next year
- I have added random star rating for special packages
Static dates and ratings not looking good
- [ x ] I have followed code style of this project.
- [ x ] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [ x ] All the aspects mentioned in the issue are covered.
- [ x ] The website is properly working after my changes.
- [ x ] 🌟 ed the repo
- [ x ] Bug fix (non-breaking change which fixes an issue)

Random dates and ratings on special packages

---

Contributing.md

- Issue No. #331 
-  In the contributing.md section, I added the links to useful blogs, Youtube videos and GitHub repositories so that beginners 
do not face any difficulty while contributing.

Added links to useful resources in Contributing.md

---

favourites.html

- Issue No. #332 
- 
added the favicon image and also added some inline style. 
Favicon is visible in homepage header.

fixed the favicon in homepage

---

favourites.html

Reverts Arun9739/Paryatana#336

Revert "fixed the favicon in homepage"

---

contact.html

- Issue No. #342
- Links added which open particular social media accounts.
it will open a new home page for all social media except Google+ because Google+ is now not available.

Links Added to 'contact for tours' section

---

index.html
tours.html

- Issue No. #338
- Added favicon in tour and homepage.
Earlier the favicon was not visible in title, now it is visible.
Favicon is visible.

favicon visible in the homepage and tour page.

---

about.html
contact.html
css/logo.css
favourites.html
index.html
tours.html

- Issue No. #340 
- removed inline style of the logo image from all html files and used an id to link to CSS logo file

fix issue #340 Logo placement is wrong

---

css/hero.css
css/logo.css

- Issue No. #
#348 
- Resposive Header
Using media  query
- [x ] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x ] All the aspects mentioned in the issue are covered.
- [x ] The website is properly working after my changes.
- [x ] 🌟 ed the repo

Haeder logo responsive

---

README.md
css/hero.css

- Issue No. #350 
- 1. Update README.md(made some changes to beautify it).
- 2. Add black color to description font .also changed font family and font weight.
- 3. Curved border of buttons in landing page.

Update hero.css and README.md

---

README.md

- Issue No. #354 
- Updated the readme file for better readability

made changes to the readme.md file

---

css/footer.css
css/hero.css

- Issue No. #357
- Changed CSS of footer to make mobile responsive.
- Centered List of pages.
- reduce margin of social media handles.
- separated input field and button.

mobile responsive footer

---

tours.html

- Issue No. #105
- Fixed Tour cards responsiveness for sm and xs.
I started by changing the size of the cards for aligning them perfectly in different viewpoints for col-sm to begin with them I found that the issue prevailed for col-sm too. so, I did the desired changes there too.
- [ x] 🌟 ed the repo
- [ x] Bug fix (non-breaking change which fixes an issue)

Fixed the responsiveness of tour package cards

---

css/footer.css

- Issue No. #298
- Email and submit buttons are adjusted in two rows.
I had separated the email and submit buttons into two rows as mentioned in issue 298.
- [x ] I have read the [**CONTRIBUTING**](https://github.com/Arun9739/Paryatana/blob/main/Contributing.md) document.
- [x ] All the aspects mentioned in the issue are covered.
- [x ] 🌟 ed the repo
- [ x] Bug fix (non-breaking change which fixes an issue)

change the subscribe our  newsletter responsiveness

---

about.html
css/templatemo-style.css

- Issue No. #362 
- 
I changed the navlinks hover effect and aligned the social icons in about us section page.
As it is not looking like an official or company-based website with those things.
- [ x] 🌟 ed the repo
- [ x] New feature (non-breaking change which adds functionality)

fixed navbar styling
